### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by espeed**

### CODE REVIEW

**Comment by ghost** [comment]
Good new James,

will look into it over the wekend, next year :)

Cheers and HNY,

/peter neubauer

Google:neubauer.peter
Skype:peter.neubauer
Phone: +46 704 106975
LinkedIn   http://www.linkedin.com/in/neubauer
Twitter      @peterneubauer

brew install neo4j && neo4j start
heroku addons:add neo4j

On Fri, Dec 30, 2011 at 11:06 PM, James Thornton
reply@reply.github.com
wrote:

**Comment by peterneubauer** [comment]
Nice.
will look into putting this into the general docs too, so we can get it into the main manual and distribution when things stabilize.

**Comment by espeed** [comment]
Hi Peter -

There are still a few things I need to clean up.

For example, I left the old Gremlin-Groovy scripts in there commented
out, as well as my initial translations into Gremlin-Java-in-Groovy.
It would be good to do a side-by-side comparison page of three Gremlin
dialects. I'll pull those out and put them into a separate doc.

There still 6 ignored functional tests -- I should have time this
weekend to finish those up.

Happy NYE!
- James

On Sat, Dec 31, 2011 at 4:25 AM, Peter Neubauer
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
Cool,
also I still get compile errors with sun. Org.Mozilla...

Cheers

/peter

Sent from a device with crappy keyboard and autocorrect
On Dec 31, 2011 2:47 PM, "James Thornton" <
reply@reply.github.com>
wrote:

**Comment by espeed** [comment]
On Sat, Dec 31, 2011 at 8:24 AM, Neo4j build server
reply@reply.github.com
wrote:

> Cool,
> also I still get compile errors with sun. Org.Mozilla...

Yeah, that was giving me issues as well. In

In JSToRepresentaitonConverter.java there is a NativeArray import...

import sun.org.mozilla.javascript.NativeArray;
//import org.mozilla.javascript.NativeArray;

Originally I was using org.mozilla.javascript.NativeArray, but I had
to switch it the other day because the script engine was returning
sun.org.mozilla.javascript.NativeArray.

For your environment, you might have to switch the import back.

As I understand it, Rhino is included by default in the Java JSR223
script engine -- it's the only scripting language that is -- all the
others, such as Groovy, you have to add manually.

Sun's version of Rhino differs from Mozilla's in a few ways...

http://stackoverflow.com/questions/4801037/sun-org-mozilla-rhino-and-extending-java-abstract-classes

So depending on your environment, you may need to switch the import back.

I asked on the Rhino newsgroup about this, but didn't get a response.
-  James

**Comment by ghost** [comment]
Mmh,
feels this is a strange issue. Let's figure that out.

Cheers,

/peter neubauer

Google:neubauer.peter
Skype:peter.neubauer
Phone: +46 704 106975
LinkedIn   http://www.linkedin.com/in/neubauer
Twitter      @peterneubauer

brew install neo4j && neo4j start
heroku addons:add neo4j

On Sat, Dec 31, 2011 at 3:57 PM, James Thornton
reply@reply.github.com
wrote:

**Comment by espeed** [comment]
I switched it back to mozilla's native array package and pushed it to
GitHub. As an experiment, please confirm that it compiles for you.

Thanks.
- James

On Sat, Dec 31, 2011 at 9:16 AM, Neo4j build server
reply@reply.github.com
wrote:

> Mmh,
> feels this is a strange issue. Let's figure that out.
> 
> Cheers,
> 
> /peter neubauer
> 
> Google:neubauer.peter
> Skype:peter.neubauer
> Phone: +46 704 106975
> LinkedIn   http://www.linkedin.com/in/neubauer
> Twitter      @peterneubauer
> 
> brew install neo4j && neo4j start
> heroku addons:add neo4j
> 
> On Sat, Dec 31, 2011 at 3:57 PM, James Thornton
> reply@reply.github.com
> wrote:
> 
> > On Sat, Dec 31, 2011 at 8:24 AM, Neo4j build server
> > reply@reply.github.com
> > wrote:
> > 
> > > Cool,
> > > also I still get compile errors with sun. Org.Mozilla...
> > 
> > Yeah, that was giving me issues as well. In
> > 
> > In JSToRepresentaitonConverter.java there is a NativeArray import...
> > 
> > import sun.org.mozilla.javascript.NativeArray;
> > //import org.mozilla.javascript.NativeArray;
> > 
> > Originally I was using org.mozilla.javascript.NativeArray, but I had
> > to switch it the other day because the script engine was returning
> > sun.org.mozilla.javascript.NativeArray.
> > 
> > For your environment, you might have to switch the import back.
> > 
> > As I understand it, Rhino is included by default in the Java JSR223
> > script engine -- it's the only scripting language that is -- all the
> > others, such as Groovy, you have to add manually.
> > 
> > Sun's version of Rhino differs from Mozilla's in a few ways...
> > 
> > http://stackoverflow.com/questions/4801037/sun-org-mozilla-rhino-and-extending-java-abstract-classes
> > 
> > So depending on your environment, you may need to switch the import back.
> > 
> > I asked on the Rhino newsgroup about this, but didn't get a response.
> > -  James
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/javascript-plugin/pull/2#issuecomment-3321382
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/javascript-plugin/pull/2#issuecomment-3321472

## 

Bulbflow: A Python framework for graph databases (http://bulbflow.com)

**Pull request merged**
